title: "Kyle Marshall" # your name (or website title) here
logo: "/images/Asset%201%401.png" # your photo (or logo) here
description: >  # your text below (remove <br> elements if you don't need line breaks)
  Web Developer - Graphic Designer - Unoffical Chef
  <br><br>
  Check out my cool thoughts.
  <br><br>
  Unlimited Hope
  <br><br>
  <a href="https://www.linkedin.com/in/kmarshallport/">Let`s Connect on LinkedIn</a> 
  
theme: BBD-jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
